### ISSUE TITLE
intake detect cube

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#12]
the robot shall be able to detect if it has a cube
the robot shall be able to automatically attempt to pick up a cube, until it has a cube in it.

**Comment by edf42001** [comment]
"The robot shall visually communicate this information to the drivers"

**Comment by RedBow** [comment]
visually on the dashboard or visually with lights? indication may be more suited as part of teleop ux

**Comment by edf42001** [comment]
I'd argue that looking down at the dashboard will not happen, so it needs to be lights (but dashboard for debugging too)

**Comment by RedBow** [comment]
see #9
