### ISSUE TITLE
drive arc turn

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#13]
the robot should have a command to turn for an arc
the command should drive at a specified speed
the command should drive at a specified radius
the command should drive for a specified arc length

the command should use sensors

**Comment by edf42001** [comment]
Sure. I was thinking it would be just like turn to angle, but you specify the left and right speeds. It'd be a bit simpler, but slightly more guess-and-check-y.

**Comment by redbow-kimee** [comment]
Closed a long while ago
