### ISSUE TITLE
add intake actions to autonomous file reader

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#22]
add code to the auto file reader to read intake actions and translate them into commands to the intake subsystem.

**Comment by edf42001** [comment]
But sequential vs parallel might be hard. Or it might not be.

**Comment by RedBow** [comment]
I believe that the file structure will have a number of columns for each subsystem. for each row however, each subsystem should be able to run one action. so the drive and the intake can each do one thing on each row.

**Comment by RedBow** [comment]
or a subsystem could do nothing
