### ISSUE TITLE
turn in place with sensors

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#5]
the robot shall turn itself in place
the robot shall not move forward or backward
the robot shall stop turning after it has reached a specified angle as compared to the direction which it started turning from
the robot shall do this using a command.

**Comment by edf42001** [comment]
Arcs turns are useful too

**Comment by RedBow** [comment]
make another issue for that

**Comment by edf42001** [comment]
Should they be the same command or different commands?

**Comment by RedBow** [comment]
@edf42001 see issue #13
