### ISSUE TITLE
Pixie cam autonomous action

### ISSUE THREAD

**Issue by redbow-kimee** [Dawgma-1712/new-FRC-2018#57]
An action in the auto file to drive to a cube using pixy cam.

**Comment by edf42001** [comment]
To reduce failure risk, we will turn to where we think the cube will be approx with the gyro, then use the pixy to aim at the cube, while encoders tell us how far to go.

**Comment by redbow-kimee** [comment]
That is a possibility. We'll have to do some testing to see what's best. #60 is for writing the routine files for the pixie cam
