### ISSUE TITLE
drive for time

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#6]
the robot shall drive at the specified output level for each side of the wheels
the robot shall stop after the specified time
the robot shall use a command for this

**Comment by edf42001** [comment]
And then if there's time after that, there should be an optional rate limiter for more consistency.

**Comment by RedBow** [comment]
limit rate of what?

**Comment by edf42001** [comment]
Velocity, so the robot doesn't go from 0 to 1 in a millisecond.
