### ISSUE TITLE
LEDs 

### ISSUE THREAD

**Issue by redbow-kimee** [Dawgma-1712/new-FRC-2018#61]
Use arduino pro mini to make LED patterns. And use that to indicate things to the audience/drivers.

**Comment by redbow-kimee** [comment]
Googeley eyes?!

**Comment by redbow-kimee** [comment]
Perhaps two sets of lights. One for indicating the elevator action (go to which position or manual control) and one for intake (in/out and has/does not have cube) discuss...

**Comment by edf42001** [comment]
http://www.revrobotics.com/rev-11-1105/ is actually what we'd be using

**Comment by redbow-kimee** [comment]
Button to flash LEDs

**Comment by redbow-kimee** [comment]
I think Bellini wants you to work with an arduino, but I have no preference either way.
