### ISSUE TITLE
move elavator to position

### ISSUE THREAD

**Issue by RedBow** [Dawgma-1712/new-FRC-2018#7]
the robot shall move the elevator to a specified position
the driver station shall have a number of buttons to specify preset positions
the robot shall use a command for this

**Comment by edf42001** [comment]
What do you mean by "the dashboard shall have a number of buttons to specify preset positions"?

**Comment by RedBow** [comment]
the driver station. and there should be buttons move the elavator to a specific height. for example to the height of the scale or the height of the exchange. see #9

**Comment by edf42001** [comment]
Does driver station = joysticks or the driver station software?

**Comment by RedBow** [comment]
both. see #9

**Comment by edf42001** [comment]
Buttons on the joystick, not on the computer

**Comment by RedBow** [comment]
closed
